gantt
    title Capstone Project
    dateFormat  DD-MM-YY
    section Planning
    Meeting with pharmacy owner : 03-03-2024, 1d
    Prepare Brief     :done ,after a1  , 1d
    Check with owner :done,  1d
    Confirm requirements :done, 1d
    Prepare Planning docs and diagrams :done, 1d
    
   


    section Design and Build
    ER Diagrams / Flow     :done, 09-03-24, 1d
    CHeck Docs and Update     :done, 1d
    Start backend build :done, 3d
    MSSQL backend complete (Stock and Specials) :done, milestone, 3d
    Specials (Printing and connection): done, 1d
    Stock Details : done, 3d 
    Stock Module Complete : done, milestone, 1d
    Posts Backend :done, 1d
    Posts Front End :done, 6d

    section Review Collate Docs
    Get docs loaded onto repo : 3d
    presentation prepared :1d
    final checks before preso :1d

    section Presentation
    Present : milestone, 07-04-24




