journey
    title Printing Shelf Labels
    section Prepare Print Job
     Open Specials on POS: 5: Staff
     Run export to CSV: 3
     Copy CSV to Mail Merge Folder: 3
    section Word Document
      Use template and import CSV: 2: Me
      Pray settings are the same: 3: Me
      Toggle margins and sizes: 3: Me
      PRINT to PDF and send to shop: 4: Me



         